In [1]:
import numpy as np

### FITS Files and Matrices


A matrix is a two-dimensional array of numbers arranged in rows and columns. Each element in the matrix can be identified by its row and column indices. Matrices are fundamental mathematical objects used in various fields such as linear algebra, computer graphics, statistics, and machine learning.


In the context of FITS files, which are commonly used in astronomy to store image data, a matrix is particularly useful for representing the pixel values of the image. Each element of the matrix corresponds to a pixel in the image, and the value of the element represents the intensity or brightness of that pixel. By arranging pixel values in a matrix, we can efficiently store and manipulate image data.

First we are going to make a matrix by using np.array

In [4]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Display the matrix
print("Original Matrix:")
print(matrix)
print()

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



There are many different ways that we can select elements from a matrix

In [9]:
# Selecting based on position
# matrix[row, column]
# Both rows and columns start at 0

matrix[0, 1]

2

In [10]:
# Selecting a row

matrix[0, :]

array([1, 2, 3, 4])

In [11]:
# Selecting a column

matrix[:, 0]

array([ 1,  5,  9, 13])

In [12]:
# Selecting the last value

matrix[-1, -1]

16

In [16]:
# Selecting the last row or column

matrix[-1, :]

array([13, 14, 15, 16])

In [17]:
matrix[:, -1]

array([ 4,  8, 12, 16])

In [15]:
# Selecting a penultimate row or column

matrix[-2, :]

array([ 9, 10, 11, 12])

In [14]:
matrix[:, -2]

array([ 3,  7, 11, 15])

In [19]:
# Selecting above a certain value

matrix[matrix>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16])

In [20]:
# Selecting a value and above

matrix[matrix>=7]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
# Selecting a range of values less than 7 and greater than 12

matrix[(matrix<7) | (matrix>12)]

array([ 1,  2,  3,  4,  5,  6, 13, 14, 15, 16])

### Transposed Matrix


Transposing a matrix involves flipping its rows and columns. This operation converts rows into columns and columns into rows, effectively changing the orientation of the matrix. If a matrix has dimensions m x n, its transpose will have dimensions n x m.

In [27]:
matrix.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

### NaN Values


A "NaN" value stands for "Not a Number." It is a special floating-point value used to represent undefined or unrepresentable numerical results, typically resulting from arithmetic operations involving undefined quantities, such as zero divided by zero or infinity minus infinity.

In [28]:
B = np.asarray([[np.nan, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, np.nan]])
B

array([[nan,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., nan]])

In [29]:
# Selecting number values only

B[np.isfinite(B)]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15.])

In [30]:
# OR

B[~np.isnan(B)]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15.])

## Introduction to Matrices is Complete


In this notebook we have covered:
- How to create a matrix
- How to transpose a matrix
- How to select a variety of values in a matrix